### ISSUE TITLE
Request: Exynos optimisation

### ISSUE THREAD

**Issue by MajorasMaks** [citra-emu/citra-android#140] opened 2020-06-06 11:56 UTC
Please optimise citra for Exynos devices, I hardly get 10 fps in almost all games, even 2D ones.

**Comment by FearlessTobi** [comment] 2020-06-06 17:44
We can't do much about some processors having worse performance.
Closing this as the issue is not really actionable.

**Closed by FearlessTobi** 2020-06-06 17:44 UTC
