### ISSUE TITLE
Shin megami tensei 4 crash bug

### ISSUE THREAD

**Issue by saintbepis** [citra-emu/citra-android#7] opened 2020-05-23 02:34 UTC
The original shin megami tensei 4 will crash the citra app back to the game selection screen when loading a save file

**Comment by BreadFish64** [comment] 2020-05-23 04:25
Duplicate of #4

**Comment by saintbepis** [comment] 2020-05-23 04:28
> Duplicate of #4

Smt overclocked and smt 4 are different games

**Comment by BreadFish64** [comment] 2020-05-23 04:58
Ah, my mistake

**Comment by saintbepis** [comment] 2020-05-23 04:59
> Ah, my mistake

It's cool no worries

**Comment by Perturbator666** [comment] 2020-05-27 22:29
Fixed on Beta 3

**Closed** 2020-05-27 22:30 UTC
Labels: bug
