### ISSUE TITLE
[Feature request] Analog pads required to map control sticks and d pad - let us map keys

### ISSUE THREAD

**Issue by consideredwords** [citra-emu/citra-android#200] opened 2020-11-07 11:16 UTC
In Citra Android you can't map keys to the stick, it must be an analogue gamepad. That may be fine for most users but odd that you can't disable this option and let us use keys. Most other emulators such as Dolphin or Citra-MMJ allow keys or analogue and do not force the option.

**Comment by FearlessTobi** [comment] 2020-11-11 00:06
Duplicate of https://github.com/citra-emu/citra-android/issues/60.
If the Dpad issue will be fixed, this one will be fixed as well.

**Closed by FearlessTobi** 2020-11-11 00:06 UTC
