### ISSUE TITLE
Majora's Mask 3D Crash with Project Restoration applied

### ISSUE THREAD

**Issue by Someguy1519** [citra-emu/citra-android#123] opened 2020-05-31 03:29 UTC
As the title says, Majora's Mask 3D crashes with the Project Restoration mod applied. The game works fine without the files and I'm pretty sure I'm using the right files for my version of the game.
I have the code and exheader files applied in citra-emu/load/mods/0004000000125500/ when the crash occurs.

Citra Beta 5 (1e97111)

Snapdragon Galaxy S8+ running Android 9.0

**Comment by Someguy1519** [comment] 2020-05-31 03:31
[citra_log.txt](https://github.com/citra-emu/citra-android/files/4707057/citra_log.txt)

**Comment by FearlessTobi** [comment] 2020-05-31 15:22
Does this occur on the Desktop version as well?

**Comment by Someguy1519** [comment] 2020-05-31 16:47
> Does this occur on the Desktop version as well?

I'm unfortunately unable to test the Desktop version as the OS version my computer is on is unsupported by the latest nightly and canary versions of citra.

**Comment by BreadFish64** [comment] 2020-06-01 18:06
Closing as there's not enough information to determine whether the problem is cause by the Android port, Citra core, or the patch itself.

**Closed** 2020-06-01 18:05 UTC
