### ISSUE TITLE
Please fix online play issue of super smash Bros Please add online play online multiplayer Play feature in this app

### ISSUE THREAD

**Issue by Farukh47027** [citra-emu/citra-android#169] opened 2020-07-03 13:33 UTC

**Comment by Farukh47027** [comment] 2020-07-03 13:33
Please fix online play issue of super smash Bros
Please add online play online multiplayer Play feature in this app

**Comment by FearlessTobi** [comment] 2020-07-03 18:20
Duplicate of https://github.com/citra-emu/citra-android/issues/109.

**Closed by FearlessTobi** 2020-07-03 18:20 UTC
