### ISSUE TITLE
Hope to have the option to turn off the sound

### ISSUE THREAD

**Issue by Y826198755** [citra-emu/citra-android#163] opened 2020-06-22 05:53 UTC
Hope to have the option to turn off the sound

**Comment by FearlessTobi** [comment] 2020-06-22 20:21
This is already possible by using the volume controls of your phone.
Also duplicate of https://github.com/citra-emu/citra-android/issues/30.

**Closed by FearlessTobi** 2020-06-22 20:21 UTC

**Comment by saintbepis** [comment] 2020-06-22 20:25
> This is already possible by using the volume controls of your phone.
> Also duplicate of https://github.com/citra-emu/citra-android/issues/30.

I think he means to turn off the actual sound emulation, alot of people want to listen to music without listening to the games on their phone and to do that they need an option in the app. 
Currently only Samsung phones can turn off individual app sounds.

**Comment by Y826198755** [comment] 2020-06-23 00:50
Controlled by the phone volume, this is called realization? A mobile phone can adjust the volume, but can not control the volume level of multiple apps, I want to listen to music while playing games!

**Comment by Y826198755** [comment] 2020-06-23 00:52
Controlled by the volume of the phone, which is called the implementation? Is a mobile phone can adjust the volume, but can not control the volume of multiple applications, I want to listen to music while playing games!

**Comment by Y826198755** [comment] 2020-06-23 00:53
Controlled by the volume of the phone, this is called realization? It is a mobile phone that can adjust the volume, but it can not control the volume level of multiple applications. I want to listen to music while playing!

**Comment by Y826198755** [comment] 2020-06-23 00:54
> 通过使用手机的音量控制，这已经可以实现。
> 还要复制[＃30](https://github.com/citra-emu/citra-android/issues/30)。

Controlled by the volume of the phone, this is called realization? It is a mobile phone that can adjust the volume, but it can not control the volume level of multiple applications. I want to listen to music while playing!
