### ISSUE TITLE
Feature Request- Add Screen Button to switch Screen position

### ISSUE THREAD

**Issue by HJMBgit84** [citra-emu/citra-android#113] opened 2020-05-30 04:45 UTC
Add additional button on screen to switch screens in Citra Android, with the possibility to map that button to a gamepad for fast switch screens

**Comment by FearlessTobi** [comment] 2020-05-30 14:44
Duplicate of https://github.com/citra-emu/citra-android/issues/68.
Please check the next time if an issue for the feature you're requesting already exists before opening a new one.

**Closed by FearlessTobi** 2020-05-30 14:44 UTC
