### ISSUE TITLE
Screen swapping tedium

### ISSUE THREAD

**Issue by Skilarbabcock** [citra-emu/citra-android#74] opened 2020-05-25 23:10 UTC
Having to manually go into the menu and click swap screens is terribly time consuming, especially in a game like Ocarina of time where you have to go to the second screen quite often to switch items. One of the reasons I was excited for the android version was the easier access to the second screen without having to go from controller to mouse. It a shame the desktop feature that should have been essential for the android port didn’t make it, that being screen swiping hot key.  I think a swype from the bottom gesture, (like swype from the top brings down the menu) would be good for quickly swapping between top and bottom screens. Being forced to have both screens on isn’t very fun either.

**Comment by FearlessTobi** [comment] 2020-05-25 23:15
Duplicate of https://github.com/citra-emu/citra-android/issues/68.

**Closed by FearlessTobi** 2020-05-25 23:15 UTC
