### ISSUE TITLE
Feature request Cheats: enable, disable placeholder till gui is ported 

### ISSUE THREAD

**Issue by abhilashkatta** [citra-emu/citra-android#115] opened 2020-05-30 08:23 UTC
A placeholder feature to enable disable cheats till the gui is ported. Saving with certain cheats enable is leading to corruption of save data. So a blanket enable disable function could be implemented just to change the add and remove the enable string.

**Comment by FearlessTobi** [comment] 2020-05-30 14:35
Duplicate of https://github.com/citra-emu/citra-android/issues/27.
I am working on porting the cheats UI properly already.

**Closed by FearlessTobi** 2020-05-30 14:35 UTC
