### ISSUE TITLE
Some Water pokemon are color white

### ISSUE THREAD

**Issue by shintzu04** [citra-emu/citra-android#181] opened 2020-08-14 21:09 UTC
![Screenshot_2020-08-15-05-05-11-55_d4f2be808e8ee95dffc2e61a2b7efef4](https://user-images.githubusercontent.com/69697440/90292776-29cd7900-deb5-11ea-82b9-bdb7d5b45fea.jpg)

Im using the Citra Emulator available in Playstore. Also i bought the premium for support.

Im using RealMe 5 pro 8GBRam phone.

Thank You.

**Comment by FearlessTobi** [comment] 2020-08-24 12:24
Thanks for your report. 
This is a duplicate of https://github.com/citra-emu/citra-android/issues/97.

**Closed by FearlessTobi** 2020-08-24 12:24 UTC
