### ISSUE TITLE
Request save state

### ISSUE THREAD

**Issue by Lemoncak3** [citra-emu/citra-android#173] opened 2020-07-18 22:42 UTC
Although 3ds games support ingame suspend save but sometimes it won't work in all places. Just hope for this feature so i can play wherever and whenever. Thanks.

**Comment by FearlessTobi** [comment] 2020-07-19 00:49
Duplicate of https://github.com/citra-emu/citra-android/issues/40.

**Closed by FearlessTobi** 2020-07-19 00:49 UTC
