### ISSUE TITLE
Haptic Feedback for On Screen Controls

### ISSUE THREAD

**Issue by bugreportanon** [citra-emu/citra-android#189] opened 2020-10-04 10:02 UTC
Pretty self explanatory, just haptic feedback/vibration for the on screen controls so you can "feel" whatever button you're pressing, ideally you should be able to adjust the vibration strength as well so you can have strong or weak vibration depending on preference.

**Comment by SachinVin** [comment] 2020-10-04 11:01
Duplicate of #96

**Closed by SachinVin** 2020-10-04 11:01 UTC
