### ISSUE TITLE
Including the play billing library infringes on the GPL

### ISSUE THREAD

**Issue by bylaws** [citra-emu/citra-android#170] opened 2020-07-11 16:15 UTC
Citra uses the play billing library 2.2 to handle it's premium in app purchase, however all versions since 2.1 are proprietary and cannot be included in GPL projects. Unfortunately billing library does not fall under the system library exception as it isn't bundled with the android system.

Ideally something like a seperate, paid, app as an unlocker could be used, similar to ppsspp.

See here for more information: https://www.xda-developers.com/f-droid-android-apps-google-play-purchases/

**Comment by FearlessTobi** [comment] 2020-07-11 16:22
Duplicate of https://github.com/citra-emu/citra-android/issues/33.
Please use the search feature the next time you open an issue.

**Closed by FearlessTobi** 2020-07-11 16:22 UTC

**Comment by bylaws** [comment] 2020-07-11 16:36
Oh lol I was looking through the issues in the citra (non android) repo and posted the issue on the android one
