### ISSUE TITLE
Hardware acceleration functions can not work on kirin soc?

### ISSUE THREAD

**Issue by ss8688** [citra-emu/citra-android#196] opened 2020-10-27 15:45 UTC
I use a honor 9x with kirin 820.
Enable the hardware acceleration I get 20 fps
Disable I get 20fps too.
It seems that the GPU is not working

**Comment by SachinVin** [comment] 2020-10-27 15:54
Did you restart the game after changing the settings?

**Comment by ss8688** [comment] 2020-10-27 16:01
Yes,but the citra seems have a file path bug (see https://github.com/citra-emu/citra/issues/5589 ) ,though I have moved the file to where it should be.  But I don't know if it works .

**Comment by ss8688** [comment] 2020-10-27 16:05
And it seems that disabled cpu jit function increases the fps in most cases on my phone

**Comment by ss8688** [comment] 2020-10-27 16:06
![Uploading Screenshot_20201028_000632.jpg…]()

**Comment by ss8688** [comment] 2020-10-27 16:07
![Screenshot_20201028_000632](https://user-images.githubusercontent.com/59367202/97328901-75d36b80-18b1-11eb-88aa-7e5a3313d8d0.jpg)

**Comment by ss8688** [comment] 2020-10-27 16:27
Change default storage location might causes more problems to other application s. I will after this bug is fixed

**Comment by ss8688** [comment] 2020-10-28 00:36
> Try testing after moving Citra to internal storage, this is probably an issue caused by the frontend and backend readings the config file from different locations.
> You will not be getting 20 fps when hardware acceleration is disabled, it will be wayyy lower.

@SachinVin I have test.It is the same.

**Comment by FearlessTobi** [comment] 2020-10-28 02:33
With the information available, it is not really possible to find out what this bug is caused by. 
Therefore I'll close this for now.

You're still able to chat here though or you can join our forums or our Discord server.

**Closed by FearlessTobi** 2020-10-28 02:33 UTC

**Comment by ss8688** [comment] 2020-10-28 04:23
@FearlessTobi Can you fix the file path bug first？

**Comment by ss8688** [comment] 2020-10-28 10:22
I have  a video shows this problem

https://pan.baidu.com/s/1BW0FFivT02KNGg4BMVoP3Q  
password:u998

**Comment by ss8688** [comment] 2020-10-28 10:23
@SachinVin @FearlessTobi 
I have a video shows this problem.

https://pan.baidu.com/s/1BW0FFivT02KNGg4BMVoP3Q 
password:u998
